import { RGBA, SyntaxStyle } from "@opentui/core";

export function createSyntaxStyle(): SyntaxStyle {
	return SyntaxStyle.fromStyles({
		default: { fg: RGBA.fromHex("#cdd6f4") },
		comment: { fg: RGBA.fromHex("#6c7086"), italic: true },
		number: { fg: RGBA.fromHex("#fab387") },
		boolean: { fg: RGBA.fromHex("#fab387") },
		constant: { fg: RGBA.fromHex("#fab387") },
		string: { fg: RGBA.fromHex("#a6e3a1") },
		character: { fg: RGBA.fromHex("#a6e3a1") },
		keyword: { fg: RGBA.fromHex("#cba6f7"), bold: true },
		operator: { fg: RGBA.fromHex("#89dceb") },
		function: { fg: RGBA.fromHex("#89b4fa") },
		"function.call": { fg: RGBA.fromHex("#89b4fa") },
		"function.method.call": { fg: RGBA.fromHex("#89b4fa") },
		type: { fg: RGBA.fromHex("#f9e2af") },
		constructor: { fg: RGBA.fromHex("#f9e2af") },
		property: { fg: RGBA.fromHex("#94e2d5") },
		"variable.member": { fg: RGBA.fromHex("#94e2d5") },
		punctuation: { fg: RGBA.fromHex("#bac2de") },
		"punctuation.bracket": { fg: RGBA.fromHex("#bac2de") },
		"punctuation.delimiter": { fg: RGBA.fromHex("#a6adc8") },
		"markup.heading": { fg: RGBA.fromHex("#89b4fa"), bold: true },
		"markup.heading.1": { fg: RGBA.fromHex("#89b4fa"), bold: true },
		"markup.heading.2": { fg: RGBA.fromHex("#74c7ec"), bold: true },
		"markup.heading.3": { fg: RGBA.fromHex("#94e2d5"), bold: true },
		"markup.list": { fg: RGBA.fromHex("#f38ba8") },
		"markup.quote": { fg: RGBA.fromHex("#6c7086"), italic: true },
		"markup.bold": { fg: RGBA.fromHex("#f5e0dc"), bold: true },
		"markup.strong": { fg: RGBA.fromHex("#f5e0dc"), bold: true },
		"markup.italic": { fg: RGBA.fromHex("#f5e0dc"), italic: true },
		"markup.link": { fg: RGBA.fromHex("#89b4fa"), underline: true },
		"markup.link.url": { fg: RGBA.fromHex("#89b4fa"), underline: true },
		"markup.raw": { fg: RGBA.fromHex("#a6e3a1") },
		"markup.raw.block": { fg: RGBA.fromHex("#a6e3a1") },
	});
}
